### ISSUE TITLE
Grunt problem

### ISSUE THREAD

**Issue by mrseth** [thevenmuthu/angular-material-seed#1]
grunt
ReferenceError: grunt is not defined
    at repl:1:1
    at REPLServer.defaultEval (repl.js:164:27)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval](domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:393:12)
    at emitOne (events.js:82:20)
    at REPLServer.emit (events.js:169:7)
    at REPLServer.Interface._onLine (readline.js:210:10)
    at REPLServer.Interface._line (readline.js:549:8)
    at REPLServer.Interface._ttyWrite (readline.js:826:14)

Any idea? Thanks so much!

**Comment by thevenmuthu** [comment]
Hello. Can you check the directory in which you run the command? It should be the root folder.

**Comment by mrseth** [comment]
yeah its the root folder :(

**Comment by weijyewang** [comment]
@sethual have you tried to do `npm install`.
Remember to do `npm install grunt-cli -g` as well and try again.
